# Generated by Django 2.1.5 on 2021-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('KOREAN', 'Korean'), ('RUSSIAN', 'Russian'), ('CHINESE', 'Chinese')], max_length=10),
        ),
    ]
