# Generated by Django 3.1.5 on 2022-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211012_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.CharField(blank=True, choices=[('U', 'U'), ('UA', 'U/A'), ('A', 'A'), ('R', 'R')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('KOREAN', 'Korean'), ('RUSSIAN', 'Russian'), ('CHINESE', 'Chinese')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity_index',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='run_length',
            field=models.IntegerField(blank=True, help_text='Enter run length in minutes'),
        ),
    ]
