# Generated by Django 3.1.5 on 2022-03-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20220309_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(null=True),
        ),
    ]
