# Generated by Django 3.1.5 on 2022-03-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20220309_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='youtube.com'),
        ),
    ]
