# Generated by Django 3.2.7 on 2021-09-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_auto_20210924_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='city',
            field=models.CharField(choices=[('MOSCOW', 'Moscow'), ('STPETERSBURG', 'StPetersBurg')], max_length=20),
        ),
    ]
