# Generated by Django 3.2.5 on 2022-02-21 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_alter_theatre_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 21, 20, 9, 5, 794412)),
        ),
    ]
