# Generated by Django 2.0.3 on 2022-02-21 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_auto_20220221_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 21, 21, 26, 42, 594269)),
        ),
    ]
